// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY65_W9jAYPSb9Si6idrLa6B5tjv6rIiA',
    appId: '1:627495058736:web:150889c7aa5d06dc8b9cf5',
    messagingSenderId: '627495058736',
    projectId: 'form-bridge-21930',
    authDomain: 'form-bridge-21930.firebaseapp.com',
    storageBucket: 'form-bridge-21930.firebasestorage.app',
    measurementId: 'G-G57Q80NQBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEjhcVb9Q48VRWxkoCkWBdrvGpwo3_xME',
    appId: '1:627495058736:android:516e648cedb7b6ab8b9cf5',
    messagingSenderId: '627495058736',
    projectId: 'form-bridge-21930',
    storageBucket: 'form-bridge-21930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9zoV8aMSxkV_fr7zMKK4Lxzg9G2qJIg',
    appId: '1:627495058736:ios:f04ea3da6b98c7bf8b9cf5',
    messagingSenderId: '627495058736',
    projectId: 'form-bridge-21930',
    storageBucket: 'form-bridge-21930.firebasestorage.app',
    iosBundleId: 'com.formpulse.mobile',
  );
}
